name: Lint-SV

on:
  push:
    branches:
      - main
      - 'stable/**'
  pull_request:
    branches:
      - main
      - 'stable/**'

jobs:
  lint:
    name: Run lint
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Install dependencies
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install -y g++-13 cmake python3
    - name: Install slang
      run: |
        git clone https://github.com/MikePopoloski/slang.git
        cd slang
        mkdir build
        cd build
        cmake ..
        make -j$(nproc)
        sudo make install
    - name: Install nox
      run: pip install --upgrade nox
    - name: Run Lint
      run: nox -s "run_slang"
