name: Lint-SV

on:
  push:
    branches:
      - main
      - 'stable/**'
  #pull_request:
    #branches:
      #- main
      #- 'stable/**'

jobs:
  lint:
    name: Run lint
    runs-on: [self-hosted, ubuntu-22.04]
    #runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Set up Python '3.12'
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y g++-13 cmake
    - name: Install slang
      run: |
        git clone https://github.com/MikePopoloski/slang.git
        cd slang
        mkdir build
        cd build
        cmake ..
        make -j$(nproc)
        sudo make install
    - name: Install nox
      run: pip install --upgrade nox
    - name: Run Lint
      run: nox -s "sv_lint"
